Pin PyScript
beeware/briefcase-web-static-template pull request #16
Opened 2024-10-11 17:27 UTC by rmartin16

## Changes
- PyScript deprecated `latest` and requires pinning for newer versions
- `<py-script>` can just be `<script type="py">` now
- PyScript now enables a top-level loop by default; I added `async="false"` to disable it
- `<py-config>` isn't necessary since it can be specified via `<script type="py" config="pyscript.toml">`

## Notes
- I think that ideally the PyScript version would live in Briefcase...or via the method I'm working on in https://github.com/beeware/briefcase/pull/1943. But I'll leave that to future work I think
- I can't figure out a good method to stop Toga's warnings from showing in the page content
  - Although, if I add `import warnings; warnings.filterwarnings("ignore")` to `index.html`....that'll work...

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

2024-10-11 17:37 UTC, rmartin16 commented
Also, I'm a bit mystified by PyScript's configuration. For instance, I find the PR where `[splashscreen]` was apparently added and where `autoclose` would be implemented in the code....but I can't find any reference to it in the documentation....so, I don't know if this is still valid config. Similarly, I don't know if `terminal = false` still does anything; they added a `terminal` attribute for the `<script type="py">` tag 🤷🏼‍♂️

2024-10-12 06:08 UTC, freakboy3742 commented
> Also, I'm a bit mystified by PyScript's configuration. For instance, I find the PR where `[splashscreen]` was apparently added and where `autoclose` would be implemented in the code....but I can't find any reference to it in the documentation....so, I don't know if this is still valid config. Similarly, I don't know if `terminal = false` still does anything; they added a `terminal` attribute for the `<script type="py">` tag 🤷🏼‍♂️

Pyscript has definitely gone through some big changes since I last did a big Toga update; most of those changes have been very welcome (distancing "getting Python working in the browser" from "having opinions about look and feel"). So - the splash screen handling has definitely been removed; and terminal handling has... changed. Part of that seems to be a new default handler for `stderr` which puts stderr content into the DOM. All documentation says should be possible to disable with `plugins = ["!error"]`... but this doesn't seem to be working for me. The simple fix is to add a `div.py-error { display: none }` CSS modification; but that doesn't seem ideal. I've poked PyScript support to get some guidance on this. 

However, we also need to fix some other issues that have slipped in as a result of API updates.
* Button handlers no longer seem to work. Pressing the button on Tutorial 0 doesn't cause anything to appear in the console.
* Style appears to have been lost from dialogs. The about dialog in Tutorial 0 displays in "browser default serif", not the Shoelace sans-serif default.
* We probably need to add a Splash screen, so that we don't get a blank page on load. 

On the last point, I'm not sure if that should be a Toga concern or a Briefcase concern - at least for the moment, I suspect it needs to be a Briefcase concern, because Toga can't provide any code that will contribute to the "pre-javascript executing" state of the page. I started looking broadly at this problem in beeware/briefcase#1285; that set of changes would provide a mechanism for a wheel to contribute content to the Briefcase-generated HTML. However, I've been distracted with Py3.13 and getting binary wheels working for the last year, so I haven't been able to give the web backend the attention it needs.

2024-10-12 06:10 UTC, freakboy3742 requested changes
This is definitely a set of changes we should make; but we need to fix the behavior change issues flagged (which might require a Toga change as well to adapt how button handlers are attached)

2024-10-12 06:27 UTC, rmartin16 commented
Makes sense :) I rather doubt I will further pursue additional efforts then to bring support back up to date; I am mostly intrigued because PyScript is particularly interesting...but it's also at the edge of a lot of my knowledge. So, I'll leave to your discretion to just close this PR...or possibly expand upon it...whatever this case is fine with me.

2024-12-09 22:17 UTC, mhsmith commented
I've updated to PyScript 2024.11.1, and added a corresponding Briefcase PR to remove the obsolete configuration settings:
* https://github.com/beeware/briefcase/pull/2080

> * Button handlers no longer seem to work. Pressing the button on Tutorial 0 doesn't cause anything to appear in the console.

It works fine for me in both Chrome and Safari.

> * Style appears to have been lost from dialogs. The about dialog in Tutorial 0 displays in "browser default serif", not the Shoelace sans-serif default.

Fixed in https://github.com/beeware/toga/pull/3035.

2024-12-10 01:48 UTC, freakboy3742 approved these changes
I've made 2 small changes:

1. I've added an animation throb to the splash screen
2. I've added an initial templated pyscript.toml file that turns on the "official" way to hide error output, rather than a CSS-based approach. This config file will be overwritten by the current mainline Briefcase; but I've updated the Briefcase PR to read-and-rewrite pyscript.toml if it the template provides it. This should allow us to accomodate future pyscript.toml changes without needing a Briefcase change (unless there's a change to the format for `packages`...)

I'm happy with where this is right now; leaving for @mhsmith to cross-check and merge these changes.

2024-12-10 22:00 UTC, mhsmith commented
In that case, the CSS to hide the stderr should be unnecessary, so I've removed it.

2024-12-10 22:04 UTC, merged